### ISSUE TITLE
获取用户信息时出错, 原因: 'user'

### ISSUE THREAD

**Issue by rasiel2k** [ICE99125/tieba_checkin#1]
START RequestId: 03e36aae-3d1f-4e73-a255-6c5b18beeb10

Starting new HTTPS connection (1): tieba.baidu.com:443

https://tieba.baidu.com:443 "GET /mg/o/profile?format=json HTTP/1.1" 200 209

🤡 获取用户信息时出错, 原因: 'user'

其他正常

**Comment by ICE99125** [comment]
问题解决了! 找问题找了好久, 结果只是接口前面多了个 c 而已!! 😂
