### ISSUE TITLE
当关注的有被封禁的吧时，签到会失败

### ISSUE THREAD

**Issue by 6ccg** [ICE99125/tieba_checkin#2]
![image](https://user-images.githubusercontent.com/44950572/185787585-c030ab1d-59ea-4325-b1f7-d97f764c8665.png)

每次签到到后宫动漫就会失败

**Comment by ICE99125** [comment]
你在 tieba.py 的 205 行写上 print(rep) 看看输出什么, 我没有被封禁的情况所以不好调试

**Comment by ICE99125** [comment]
你在 tieba.py 的 205 行写上 print(res) 看看输出什么, 我没有被封禁的情况所以不好调试

**Comment by 6ccg** [comment]
🌞 开始签到贴吧 后宫动漫

Starting new HTTP connection (1): c.tieba.baidu.com:80

http://c.tieba.baidu.com:80 "POST /c/c/forum/sign HTTP/1.1" 200 None

{'error_code': '340006', 'error_msg': '贴吧目录出问题啦，请到贴吧签到吧反馈', 'info': [], 'time': 马赛克, 'ctime': 0, 'logid': 马赛克, 'server_time': '马赛克'}

ERROR RequestId: ad88a78b-8d75-4308-a181-7e78575f82d7 Result: Traceback (most recent call last):   File "/var/user/index.py", line 15, in main     res = b.start()   File "/var/user/tieba.py", line 8, in inner     res = fn(*args, **kwargs)   File "/var/user/tieba.py", line 235, in start     res = self.client_sign(favorite["id"], favorite["name"])   File "/var/user/tieba.py", line 215, in client_sign     exp = res["user_info"].get("sign_bonus_point") KeyError: 'user_info'

END RequestId: ad88a78b-8d75-4308-a181-7e78575f82d7

Report RequestId: ad88a78b-8d75-4308-a181-7e78575f82d7 Duration: 5282ms Memory: 128MB MemUsage: 16.50MB

**Comment by ICE99125** [comment]
好了

**Comment by 6ccg** [comment]
thanks,问题已解决
